### ISSUE TITLE
Trying to understand the Pledge Project.

### ISSUE THREAD

**Issue by afro-coder** [jart/pledge#3]
Hi folks,

I've not used C just Python, but I'm trying to learn along with Rust and Golang, I was redirected to this project since I'm working on trying to port various applications on Risc-v. 

I understand that we're trying to port https://man.openbsd.org/pledge.2 to Linux, having quite less knowledge on how porting works(Is it copying functions, etc?) 

I'd like to help regardless, starting from updating the readme with examples maybe of how to use Pledge then slowly move to code.

Any previous examples etc I could get some help with on how to use Pledge? I can setup stuff etc just not that good at programming.

Any tips etc will be appreciated, I'll start slowly updating Readme stuff I guess to understand the project. Thanks

**Comment by jart** [comment]
I'm glad you're excited about pledge on Linux! This issue tracker is for bugs and feature requests. Good luck on your journey learning more about SECCOMP filtering. Feel free to reach out again if you have a bug or feature request.
