### ISSUE TITLE
system_error: random_device failed to open /dev/urandom: Operation not permitted

### ISSUE THREAD

**Issue by daitj** [jart/pledge#7]
With plegde promise `stdio` llamafile should have read only access to `/dev/urandom`, I am trying to build and test llamafile using vulkan in linux, I am getting `SIGABRT` error with `system_error: random_device failed to open /dev/urandom: Operation not permitted.`
﻿
Is it pledge issue or llamafile issue?
[llama-vulkan.log](https://github.com/user-attachments/files/15855187/llama-vulkan.log)

**Comment by jart** [comment]
`pledge("stdio", 0)` forbids all filesystem access. That includes `/dev/urandom`. I've confirmed this is also the case on OpenBSD. There is no bug. You need to either:

1. Open a file descriptor to `/dev/urandom` *before* calling pledge().
2. Consider `RDRND`

It's highly unlikely that you're going to get GPU support to work with pledge(). By default, llamafile disables all security features when you use GPU. I imagine Vulkan would have even more security surface area.
